module 4 tasks 1, 2, 3
js-tasks-ru/jsbasic-20210225_yuriy-yupiter pull request #5
Opened 2021-03-13 16:49 UTC by Yupiter78

2021-03-13 16:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-14 17:36 UTC, SinimaWath requested changes

2021-03-14 17:36 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    });
А зачем здесь переменная `nameFrietnd`?

2021-03-14 17:36 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  }
Хорошее решение, но давай для практики переделаем на спред: `...` и `forEach`

2021-03-14 17:36 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    let row = table.rows[i];
Это const

2021-03-16 18:59 UTC, SinimaWath approved these changes

2021-03-16 19:00 UTC, merged