module 7 task 1, 2, 3, 4 ver.1.0
js-tasks-ru/jsbasic-20210225_yuriy-yupiter pull request #8
Opened 2021-04-03 16:46 UTC by Yupiter78

2021-04-03 17:20 UTC, SinimaWath requested changes
Давай везде разделим Внутренние и Внешние свойства и методы
Внутрении свойства/мтеоды, который не используются пользователями(тестами) - приватные:
- можно сделать через `_` в начале
- можно сделать через `#`

2021-04-03 17:20 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    this.value = '';
А зачем нужна это свойство?

Я как вижу по коду, оно используется в одном месте: `this.value = itemElem.dataset.id`;

И там можно обойтись обычной переменной, а не свойством

2021-04-03 17:20 UTC, SinimaWath commented on 7-module/3-task/index.js
> +    this.setValue(this.value);
Это приватные свойства и методы

2021-04-03 17:20 UTC, SinimaWath commented on 7-module/2-task/index.js
> +  onKeyDownEscape = (event) => {
Приватные методы

2021-04-03 17:20 UTC, SinimaWath commented on 7-module/4-task/index.js
> +    }
Выше уже импортируется необходимый helper. Зачем создавать в рамках функции render?

2021-04-03 17:35 UTC, Yupiter78 commented on 7-module/4-task/index.js
> +    }
Забыл убрать эту функцию перед отправкой. 
Работаю в Webstorm,  не создавал локальный сервер и для работы необходимые модули сохраняю в одном файле.

2021-04-03 17:37 UTC, Yupiter78 commented on 7-module/3-task/index.js
> +    this.setValue(this.value);
Пока не очень хорошо понимаю деление на внешние и приватные свойства.

2021-04-03 22:41 UTC, Yupiter78 commented
Приватные свойства через хэш# пришлось объявить до конструктора, иначе выдавал ошибку.

2021-04-04 14:31 UTC, SinimaWath approved these changes
Внутренний - это тот интерфейс, который ты не даешь видеть пользователям твоего класса. 

К примеру класс StepSlider.

Все что от тебя требуется для этого класса, это:

`elem` - свойство.

 И генерировать `slider-change`

Остальные методы/свойства - приватные

2021-04-04 14:31 UTC, SinimaWath commented on 7-module/3-task/index.js
> +  #value;
Свойства, всегда лучше инициализировать значениями по-умолчанию: `#steps = null`;

2021-04-04 14:32 UTC, merged

2021-04-04 16:30 UTC, Yupiter78 commented on 7-module/3-task/index.js
> +  #value;
Ок, спасибо!