module 8 task 1, 2, 3, 4
js-tasks-ru/jsbasic-20210225_yuriy-yupiter pull request #9
Opened 2021-04-06 16:43 UTC by Yupiter78

2021-04-06 16:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-04-06 17:29 UTC, SinimaWath requested changes
Все хорошо, только есть маленькие замечания, давай поправим их

2021-04-06 17:29 UTC, SinimaWath commented on 8-module/1-task/index.js
> +    }
Это условие должно идти раньше чем window.pageYOffset > this.initialTopCoord

Так как если ширина меньше 767 - уже нет смысла дальше, что-то считать и можно выйти их функции через return

2021-04-06 17:29 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    Object.assign(this.filters, filters);
Давай для практики попробуем использовать здесь spread оператор

2021-04-06 17:29 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    let cartItem = this.cartItems.find(item => item.product.id == productId);
Это скорее всего должен быть const

2021-04-06 17:29 UTC, SinimaWath commented on 8-module/4-task/index.js
> +    this.modalBody.querySelector("form").onsubmit = (event) => this.onSubmit(event);
А не проще будет сделать onSubmit стрелочным методом?

2021-04-07 18:28 UTC, SinimaWath approved these changes
все ок!

2021-04-07 18:29 UTC, merged